version: '3'

services:
  sqlserver:
    image: sharding.sql
    build:
      context: ./src/AkkaSql
    ports:
      - '1533:1433'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: l0lTh1sIsOpenSource
      MSSQL_PID: Developer

  sharding.lighthouse:
    image: petabridge/lighthouse:latest
    hostname: sharding.lighthouse
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "ShardFight"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "sharding.lighthouse"
      CLUSTER_SEEDS: "akka.tcp://ShardFight@sharding.lighthouse:4053"

  sharding.shard:
    image: sharding.shard:latest
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://ShardFight@sharding.lighthouse:4053"
      CLUSTER_PORT: 5110
      SQL_HOSTNAME: sqlserver
      SQL_CONNECTION_STR: "Server=sqlserver;Database=Akka;User Id=sa;Password=l0lTh1sIsOpenSource;"
    restart: on-failure
    depends_on:
      - "sharding.lighthouse"
      - "sqlserver"