version: '3'

services:
  sqlserver:
    image: sharding.sql
    hostname: sharding.sqlserver
    build:
      context: ./src/AkkaSql
    ports:
      - '0:1433'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: l0lTh1sIsOpenSource
      MSSQL_PID: Developer

  sharding.lighthouse:
    image: sharding.lighthouse:latest
    hostname: sharding.lighthouse
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "ShardFight"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "sharding.lighthouse"
      CLUSTER_SEEDS: "akka.tcp://ShardFight@sharding.lighthouse:4053"

  sharding.shard:
    image: sharding.shard:latest
    environment:
      CLUSTER_SEEDS: "akka.tcp://ShardFight@sharding.lighthouse:4053"
      CLUSTER_PORT: 0
      SQL_CONNECTION_STR: "Server=sharding.sqlserver;Database=Akka;User Id=sa;Password=l0lTh1sIsOpenSource;"
    depends_on:
      - "sharding.lighthouse"
      - "sqlserver"